export default [
  { akc_code: 501, title: "Affenpinscher", value: "affenpinscher" },
  { akc_code: 401, title: "Afghan Hound", value: "afghan-hound" },
  { akc_code: 201, title: "Airedale Terrier", value: "airedale-terrier" },
  { akc_code: 630, title: "Akita", value: "akita" },
  { akc_code: 601, title: "Alaskan Malamute", value: "alaskan-malamute" },
  { akc_code: 673, title: "American Bulldog", value: "American-bulldog" },
  {
    akc_code: 425,
    title: "American English Coonhound",
    value: "american-english-coonhound",
  },
  { akc_code: 316, title: "American Eskimo Dog", value: "american-eskimo-dog" },
  { akc_code: 409, title: "American Foxhound", value: "american-foxhound" },
  {
    akc_code: 231,
    title: "American Hairless Terrier",
    value: "american-hairless-terrier",
  },
  {
    akc_code: 445,
    title: "American Leopard Hound",
    value: "american-leopard-hound",
  },
  {
    akc_code: 202,
    title: "American Staffordshire Terrier",
    value: "american-staffordshire-terrier",
  },
  {
    akc_code: 112,
    title: "American Water Spaniel",
    value: "american-water-spaniel",
  },
  {
    akc_code: 635,
    title: "Anatolian Shepherd Dog",
    value: "anatolian-shepherd-dog",
  },
  {
    akc_code: 858,
    title: "Appenzeller Sennenhunde",
    value: "appenzeller-sennenhunde",
  },
  {
    akc_code: 832,
    title: "Australian Cattle Dog",
    value: "australian-cattle-dog",
  },
  { akc_code: 867, title: "Australian Kelpie", value: "australian-kelpie" },
  { akc_code: 834, title: "Australian Shepherd", value: "australian-shepherd" },
  {
    akc_code: 869,
    title: "Australian Stumpy-Tail Cattle Dog",
    value: "Australian-Stumpy-Tail-Cattle-Dog",
  },
  { akc_code: 203, title: "Australian Terrier", value: "australian-terrier" },
  { akc_code: 437, title: "Azawakh", value: "azawakh" },
  { akc_code: 140, title: "Barbet", value: "barbet" },
  { akc_code: 402, title: "Basenji", value: "basenji" },
  {
    akc_code: 446,
    title: "Basset Fauve de Bretagne",
    value: "basset-fauve-de-bretagne",
  },
  { akc_code: 403, title: "Basset Hound", value: "basset-hound" },
  {
    akc_code: 450,
    title: "Bavarian Mountain Scent Hound",
    value: "bavarian-mountain-scent -hound",
  },
  { akc_code: 404, title: "Beagle", value: "beagle" },
  { akc_code: 831, title: "Bearded Collie", value: "bearded-collie" },
  { akc_code: 846, title: "Beauceron", value: "beauceron" },
  { akc_code: 204, title: "Bedlington Terrier", value: "bedlington-terrier" },
  { akc_code: 843, title: "Belgian Laekenois", value: "belgian-laekenois" },
  { akc_code: 802, title: "Belgian Malinois", value: "belgian-malinois" },
  { akc_code: 803, title: "Belgian Sheepdog", value: "belgian-sheepdog" },
  { akc_code: 804, title: "Belgian Tervuren", value: "belgian-tervuren" },
  { akc_code: 841, title: "Bergamasco Sheepdog", value: "bergamasco-sheepdog" },
  { akc_code: 856, title: "Berger Picard", value: "berger-picard" },
  {
    akc_code: 605,
    title: "Bernese Mountain Dog",
    value: "bernese-mountain-dog",
  },
  { akc_code: 310, title: "Bichon Frise", value: "bichon-frise" },
  { akc_code: 548, title: "Biewer Terrier", value: "biewer-terrier" },
  {
    akc_code: 405,
    title: "Black and Tan Coonhound",
    value: "black-and-tan-coonhound",
  },
  {
    akc_code: 637,
    title: "Black Russian Terrier",
    value: "black-russian-terrier",
  },
  { akc_code: 406, title: "Bloodhound", value: "bloodhound" },
  { akc_code: 424, title: "Bluetick Coonhound", value: "bluetick-coonhound" },
  { akc_code: 659, title: "Boerboel", value: "boerboel" },
  { akc_code: 372, title: "Bohemian Shepherd", value: "bohemian-shepherd" },
  { akc_code: 521, title: "Bolognese", value: "bolognese" },
  { akc_code: 835, title: "Border Collie", value: "border-collie" },
  { akc_code: 205, title: "Border Terrier", value: "border-terrier" },
  { akc_code: 407, title: "Borzoi", value: "borzoi" },
  { akc_code: 301, title: "Boston Terrier", value: "boston-terrier" },
  {
    akc_code: 806,
    title: "Bouvier des Flandres",
    value: "bouvier-des-flandres",
  },
  { akc_code: 607, title: "Boxer", value: "boxer" },
  { akc_code: 131, title: "Boykin Spaniel", value: "boykin-spaniel" },
  { akc_code: 133, title: "Bracco Italiano", value: "bracco-italiano" },
  {
    akc_code: 144,
    title: "Braque du Bourbonnais",
    value: "braque-du-bourbonnais",
  },
  {
    akc_code: 148,
    title: "Braque Francais Pyrenean",
    value: "braque-francais-pyrenean",
  },
  { akc_code: 808, title: "Briard", value: "briard" },
  { akc_code: 113, title: "Brittany", value: "brittany" },
  { akc_code: 665, title: "Broholmer", value: "broholmer" },
  { akc_code: 502, title: "Brussels Griffon", value: "brussels-griffon" },
  { akc_code: 206, title: "Bull Terrier", value: "bull-terrier" },
  { akc_code: 302, title: "Bulldog", value: "bulldog" },
  { akc_code: 609, title: "Bullmastiff", value: "bullmastiff" },
  { akc_code: 207, title: "Cairn Terrier", value: "cairn-terrier" },
  { akc_code: 840, title: "Canaan Dog", value: "canaan-dog" },
  { akc_code: 643, title: "Cane Corso", value: "cane-corso" },
  {
    akc_code: 828,
    title: "Cardigan Welsh Corgi",
    value: "cardigan-welsh-corgi",
  },
  { akc_code: 454, title: "Carolina Dog", value: "carolina-dog" },
  {
    akc_code: 837,
    title: "Catahoula Leopard Dog",
    value: "catahoula-leopard-dog",
  },
  {
    akc_code: 644,
    title: "Caucasian Shepherd Dog",
    value: "caucasian-shepherd-dog",
  },
  {
    akc_code: 517,
    title: "Cavalier King Charles Spaniel",
    value: "cavalier-king-charles-spaniel",
  },
  {
    akc_code: 652,
    title: "Central Asian Shepherd Dog",
    value: "central-asian-shepherd-dog",
  },
  { akc_code: 228, title: "Cesky Terrier", value: "cesky-terrier" },
  {
    akc_code: 104,
    title: "Chesapeake Bay Retriever",
    value: "chesapeake-bay-retriever",
  },
  { akc_code: 503, title: "Chihuahua", value: "chihuahua" },
  { akc_code: 516, title: "Chinese Crested", value: "chinese-crested" },
  { akc_code: 314, title: "Chinese Shar-Pei", value: "chinese-shar-pei" },
  { akc_code: 653, title: "Chinook", value: "chinook" },
  { akc_code: 303, title: "Chow Chow", value: "chow-chow" },
  { akc_code: 440, title: "Cirneco dell'Etna", value: "cirneco-delletna" },
  { akc_code: 114, title: "Clumber Spaniel", value: "clumber-spaniel" },
  { akc_code: 115, title: "Cocker Spaniel", value: "cocker-spaniel" },
  { akc_code: 810, title: "Collie", value: "collie" },
  { akc_code: 318, title: "Coton de Tulear", value: "coton-de-tulear" },
  { akc_code: 868, title: "Croatian Sheepdog", value: "croation -sheepdog" },
  {
    akc_code: 105,
    title: "Curly-Coated Retriever",
    value: "curly-coated-retriever",
  },
  {
    akc_code: 663,
    title: "Czechoslovakian Vlcak",
    value: "czechoslovakian-vlcak",
  },
  { akc_code: 408, title: "Dachshund", value: "dachshund" },
  { akc_code: 304, title: "Dalmatian", value: "dalmatian" },
  {
    akc_code: 208,
    title: "Dandie Dinmont Terrier",
    value: "dandie-dinmont-terrier",
  },
  {
    akc_code: 662,
    title: "Danish-Swedish Farmdog",
    value: "danish-swedish-farmdog",
  },
  {
    akc_code: 145,
    title: "Deutscher Wachtelhund",
    value: "deutscher-wachtelhund",
  },
  { akc_code: 611, title: "Doberman Pinscher", value: "doberman-pinscher" },
  { akc_code: 638, title: "Dogo Argentino", value: "dogo-argentino" },
  { akc_code: 639, title: "Dogue de Bordeaux", value: "dogue-de-bordeaux" },
  {
    akc_code: 143,
    title: "Drentsche Patrijshond",
    value: "drentsche-patrijshond",
  },
  { akc_code: 448, title: "Drever", value: "drever" },
  { akc_code: 863, title: "Dutch Shepherd", value: "dutch-shepherd" },
  {
    akc_code: 116,
    title: "English Cocker Spaniel",
    value: "english-cocker-spaniel",
  },
  { akc_code: 410, title: "English Foxhound", value: "english-foxhound" },
  { akc_code: 109, title: "English Setter", value: "english-setter" },
  {
    akc_code: 117,
    title: "English Springer Spaniel",
    value: "english-springer-spaniel",
  },
  { akc_code: 504, title: "English Toy Spaniel", value: "english-toy-spaniel" },
  {
    akc_code: 859,
    title: "Entlebucher Mountain Dog",
    value: "entlebucher-mountain-dog",
  },
  {
    akc_code: 655,
    title: "Estrela Mountain Dog",
    value: "estrela-mountain-dog",
  },
  { akc_code: 353, title: "Eurasier", value: "eurasier" },
  { akc_code: 118, title: "Field Spaniel", value: "field-spaniel" },
  { akc_code: 848, title: "Finnish Lapphund", value: "finnish-lapphund" },
  { akc_code: 313, title: "Finnish Spitz", value: "finnish-spitz" },
  {
    akc_code: 106,
    title: "Flat-Coated Retriever",
    value: "flat-coated-retriever",
  },
  { akc_code: 305, title: "French Bulldog", value: "french-bulldog" },
  { akc_code: 146, title: "French Spaniel", value: "french-spaniel" },
  {
    akc_code: 142,
    title: "German Longhaired Pointer",
    value: "german-longhaired-pointer",
  },
  { akc_code: 636, title: "German Pinscher", value: "german-pinscher" },
  { akc_code: 812, title: "German Shepherd Dog", value: "german-shepherd-dog" },
  {
    akc_code: 102,
    title: "German Shorthaired Pointer",
    value: "german-shorthaired-pointer",
  },
  { akc_code: 319, title: "German Spitz", value: "german-spitz" },
  {
    akc_code: 103,
    title: "German Wirehaired Pointer",
    value: "german-wirehaired-pointer",
  },
  { akc_code: 613, title: "Giant Schnauzer", value: "giant-schnauzer" },
  {
    akc_code: 229,
    title: "Glen of Imaal Terrier",
    value: "glen-of-imaal-terrier",
  },
  { akc_code: 107, title: "Golden Retriever", value: "golden-retriever" },
  { akc_code: 110, title: "Gordon Setter", value: "gordon-setter" },
  {
    akc_code: 439,
    title: "Grand Basset Griffon Vendeen",
    value: "grand-basset-griffon-vendeen",
  },
  { akc_code: 614, title: "Great Dane", value: "great-dane" },
  { akc_code: 615, title: "Great Pyrenees", value: "great-pyrenees" },
  {
    akc_code: 634,
    title: "Greater Swiss Mountain Dog",
    value: "greater-swiss-mountain-dog",
  },
  { akc_code: 411, title: "Greyhound", value: "greyhound" },
  { akc_code: 444, title: "Hamiltonstovare", value: "hamiltonstovare" },
  {
    akc_code: 455,
    title: "Hanoverian Scenthound",
    value: "hanoverian-scenthound",
  },
  { akc_code: 412, title: "Harrier", value: "harrier" },
  { akc_code: 518, title: "Havanese", value: "havanese" },
  { akc_code: 669, title: "Hokkaido", value: "hokkaido" },
  { akc_code: 661, title: "Hovawart", value: "hovawart" },
  { akc_code: 420, title: "Ibizan Hound", value: "ibizan-hound" },
  { akc_code: 842, title: "Icelandic Sheepdog", value: "icelandic-sheepdog" },
  {
    akc_code: 129,
    title: "Irish Red and White Setter",
    value: "irish-red-and-white-setter",
  },
  { akc_code: 111, title: "Irish Setter", value: "irish-setter" },
  { akc_code: 210, title: "Irish Terrier", value: "irish-terrier" },
  { akc_code: 119, title: "Irish Water Spaniel", value: "irish-water-spaniel" },
  { akc_code: 413, title: "Irish Wolfhound", value: "irish-wolfhound" },
  { akc_code: 505, title: "Italian Greyhound", value: "italian-greyhound" },
  { akc_code: 249, title: "Jagdterrier", value: "jagdterrier" },
  { akc_code: 506, title: "Japanese Chin", value: "japanese-chin" },
  { akc_code: 352, title: "Jindo", value: "jindo" },
  { akc_code: 645, title: "Kai Ken", value: "kai-ken" },
  { akc_code: 657, title: "Karelian Bear Dog", value: "karelian-bear-dog" },
  { akc_code: 306, title: "Keeshond", value: "keeshond" },
  { akc_code: 211, title: "Kerry Blue Terrier", value: "kerry-blue-terrier" },
  { akc_code: 658, title: "Kishu Ken", value: "kishu-ken" },
  { akc_code: 616, title: "Komondor", value: "komondor" },
  { akc_code: 354, title: "Kromfohrlander", value: "kromfohrlander" },
  { akc_code: 617, title: "Kuvasz", value: "kuvasz" },
  {
    akc_code: 108,
    title: "Labrador Retriever (All Colors)",
    value: "labrador-retriever",
  },
  {
    akc_code: 108,
    title: "Labrador Retriever (Black)",
    value: "labrador-retriever",
  },
  {
    akc_code: 108,
    title: "Labrador Retriever (Chocolate)",
    value: "labrador-retriever",
  },
  {
    akc_code: 108,
    title: "Labrador Retriever (Yellow)",
    value: "labrador-retriever",
  },
  { akc_code: 134, title: "Lagotto Romagnolo", value: "lagotto-romagnolo" },
  { akc_code: 212, title: "Lakeland Terrier", value: "lakeland-terrier" },
  { akc_code: 849, title: "Lancashire Heeler", value: "lancashire-heeler" },
  { akc_code: 866, title: "Lapponian Herder", value: "lapponian-herder" },
  { akc_code: 654, title: "Leonberger", value: "leonberger" },
  { akc_code: 307, title: "Lhasa Apso", value: "lhasa-apso" },
  { akc_code: 317, title: "Löwchen", value: "lowchen" },
  { akc_code: 507, title: "Maltese", value: "maltese" },
  { akc_code: 213, title: "Manchester Terrier", value: "manchester-terrier" },
  { akc_code: 618, title: "Mastiff", value: "mastiff" },
  {
    akc_code: 861,
    title: "Miniature American Shepherd",
    value: "miniature-american-shepherd",
  },
  {
    akc_code: 227,
    title: "Miniature Bull Terrier",
    value: "miniature-bull-terrier",
  },
  { akc_code: 508, title: "Miniature Pinscher", value: "miniature-pinscher" },
  { akc_code: 214, title: "Miniature Schnauzer", value: "miniature-schnauzer" },
  { akc_code: 452, title: "Mountain Cur", value: "mountain-cur" },
  { akc_code: 854, title: "Mudi", value: "mudi" },
  { akc_code: 642, title: "Neapolitan Mastiff", value: "neapolitan-mastiff" },
  {
    akc_code: 135,
    title: "Nederlandse Kooikerhondje",
    value: "nederlandse-kooikerhondje",
  },
  { akc_code: 619, title: "Newfoundland", value: "newfoundland" },
  { akc_code: 216, title: "Norfolk Terrier", value: "norfolk-terrier" },
  { akc_code: 441, title: "Norrbottenspets", value: "norrbottenspets" },
  { akc_code: 838, title: "Norwegian Buhund", value: "norwegian-buhund" },
  { akc_code: 414, title: "Norwegian Elkhound", value: "norwegian-elkhound" },
  { akc_code: 330, title: "Norwegian Lundehund", value: "norwegian-lundehund" },
  { akc_code: 215, title: "Norwich Terrier", value: "norwich-terrier" },
  {
    akc_code: 128,
    title: "Nova Scotia Duck Tolling Retriever",
    value: "nova-scotia-duck-tolling-retriever",
  },
  {
    akc_code: 820,
    title: "Old English Sheepdog",
    value: "old-english-sheepdog",
  },
  { akc_code: 415, title: "Otterhound", value: "otterhound" },
  { akc_code: 509, title: "Papillon", value: "papillon" },
  {
    akc_code: 230,
    title: "Parson Russell Terrier",
    value: "parson-russell-terrier",
  },
  { akc_code: 510, title: "Pekingese", value: "pekingese" },
  {
    akc_code: 829,
    title: "Pembroke Welsh Corgi",
    value: "pembroke-welsh-corgi",
  },
  {
    akc_code: 641,
    title: "Perro de Presa Canario",
    value: "perro-de-presa-canario",
  },
  {
    akc_code: 432,
    title: "Peruvian Inca Orchid",
    value: "peruvian-inca-orchid",
  },
  {
    akc_code: 422,
    title: "Petit Basset Griffon Vendeen",
    value: "petit-basset-griffon-vendeen",
  },
  { akc_code: 421, title: "Pharaoh Hound", value: "pharaoh-hound" },
  { akc_code: 423, title: "Plott", value: "plott" },
  { akc_code: 101, title: "Pointer", value: "pointer" },
  {
    akc_code: 836,
    title: "Polish Lowland Sheepdog",
    value: "polish-lowland-sheepdog",
  },
  { akc_code: 511, title: "Pomeranian", value: "pomeranian" },
  { akc_code: 701, title: "Poodle (All Varieties)", value: "poodle" },
  { akc_code: 701, title: "Poodle (Miniature)", value: "poodle" },
  { akc_code: 701, title: "Poodle (Standard)", value: "poodle" },
  { akc_code: 701, title: "Poodle (Toy)", value: "poodle" },
  { akc_code: 451, title: "Porcelaine", value: "porcelaine" },
  { akc_code: 438, title: "Portuguese Podengo", value: "portuguese-podengo" },
  {
    akc_code: 443,
    title: "Portuguese Podengo Pequeno",
    value: "portuguese-podengo-pequeno",
  },
  { akc_code: 137, title: "Portuguese Pointer", value: "portuguese-pointer" },
  { akc_code: 864, title: "Portuguese Sheepdog", value: "portuguese-sheepdog" },
  {
    akc_code: 633,
    title: "Portuguese Water Dog",
    value: "portuguese-water-dog",
  },
  { akc_code: 147, title: "Pudelpointer", value: "pudelpointer" },
  { akc_code: 512, title: "Pug", value: "pug" },
  { akc_code: 821, title: "Puli", value: "puli" },
  { akc_code: 852, title: "Pumi", value: "pumi" },
  { akc_code: 667, title: "Pyrenean Mastiff", value: "pyrenean-mastiff" },
  { akc_code: 853, title: "Pyrenean Shepherd", value: "pyrenean-shepherd" },
  { akc_code: 656, title: "Rafeiro do Alentejo", value: "rafeiro-do-alentejo" },
  { akc_code: 247, title: "Rat Terrier", value: "rat-terrier" },
  { akc_code: 430, title: "Redbone Coonhound", value: "redbone-coonhound" },
  { akc_code: 416, title: "Rhodesian Ridgeback", value: "rhodesian-ridgeback" },
  {
    akc_code: 671,
    title: "Romanian Mioritic Shepherd Dog",
    value: "romanian-mioritic-shepherd-dog",
  },
  { akc_code: 622, title: "Rottweiler", value: "rottweiler" },
  { akc_code: 248, title: "Russell Terrier", value: "russell-terrier" },
  { akc_code: 547, title: "Russian Toy", value: "russian-toy" },
  {
    akc_code: 549,
    title: "Russian Tsvetnaya Bolonka",
    value: "russian-tsvetnaya-bolonka",
  },
  { akc_code: 623, title: "Saint Bernard", value: "saint-bernard" },
  { akc_code: 417, title: "Saluki", value: "saluki" },
  { akc_code: 624, title: "Samoyed", value: "samoyed" },
  { akc_code: 855, title: "Schapendoes", value: "schapendoes" },
  { akc_code: 309, title: "Schipperke", value: "schipperke" },
  { akc_code: 418, title: "Scottish Deerhound", value: "scottish-deerhound" },
  { akc_code: 218, title: "Scottish Terrier", value: "scottish-terrier" },
  { akc_code: 219, title: "Sealyham Terrier", value: "sealyham-terrier" },
  { akc_code: 456, title: "Segugio Italiano", value: "segugio-italiano" },
  { akc_code: 825, title: "Shetland Sheepdog", value: "shetland-sheepdog" },
  { akc_code: 315, title: "Shiba Inu", value: "shiba-inu" },
  { akc_code: 513, title: "Shih Tzu", value: "shih-tzu" },
  { akc_code: 9999, title: "Shikoku", value: "shikoku" },
  { akc_code: 626, title: "Siberian Husky", value: "siberian-husky" },
  { akc_code: 514, title: "Silky Terrier", value: "silky-terrier" },
  { akc_code: 220, title: "Skye Terrier", value: "skye-terrier" },
  { akc_code: 435, title: "Sloughi", value: "sloughi" },
  {
    akc_code: 149,
    title: "Slovakian Wirehaired Pointer",
    value: "slovakian-wirehaired-pointer",
  },
  { akc_code: 860, title: "Slovensky Cuvac", value: "slovensky-cuvac" },
  { akc_code: 449, title: "Slovensky Kopov", value: "slovensky-kopov" },
  {
    akc_code: 139,
    title: "Small Munsterlander",
    value: "small-munsterlander-pointer",
  },
  { akc_code: 225, title: "Smooth Fox Terrier", value: "smooth-fox-terrier" },
  {
    akc_code: 223,
    title: "Soft Coated Wheaten Terrier",
    value: "soft-coated-wheaten-terrier",
  },
  { akc_code: 660, title: "Spanish Mastiff", value: "spanish-mastiff" },
  { akc_code: 862, title: "Spanish Water Dog", value: "spanish-water-dog" },
  { akc_code: 132, title: "Spinone Italiano", value: "spinone-italiano" },
  { akc_code: 136, title: "Stabyhoun", value: "stabyhoun" },
  {
    akc_code: 224,
    title: "Staffordshire Bull Terrier",
    value: "staffordshire-bull-terrier",
  },
  { akc_code: 627, title: "Standard Schnauzer", value: "standard-schnauzer" },
  { akc_code: 120, title: "Sussex Spaniel", value: "sussex-spaniel" },
  { akc_code: 857, title: "Swedish Lapphund", value: "swedish-lapphund" },
  { akc_code: 844, title: "Swedish Vallhund", value: "swedish-vallhund" },
  { akc_code: 355, title: "Taiwan Dog", value: "taiwan-dog" },
  {
    akc_code: 250,
    title: "Teddy Roosevelt Terrier",
    value: "teddy-roosevelt-terrier",
  },
  { akc_code: 436, title: "Thai Ridgeback", value: "thai-ridgeback" },
  { akc_code: 640, title: "Tibetan Mastiff", value: "tibetan-mastiff" },
  { akc_code: 312, title: "Tibetan Spaniel", value: "tibetan-spaniel" },
  { akc_code: 311, title: "Tibetan Terrier", value: "tibetan-terrier" },
  { akc_code: 664, title: "Tornjak", value: "tornjak" },
  { akc_code: 647, title: "Tosa", value: "tosa" },
  { akc_code: 519, title: "Toy Fox Terrier", value: "toy-fox-terrier" },
  { akc_code: 447, title: "Transylvanian Hound", value: "transylvanian-hound" },
  {
    akc_code: 431,
    title: "Treeing Tennessee Brindle",
    value: "treeing-tennessee-brindle",
  },
  {
    akc_code: 426,
    title: "Treeing Walker Coonhound",
    value: "treeing-walker-coonhound",
  },
  { akc_code: 122, title: "Vizsla", value: "vizsla" },
  { akc_code: 123, title: "Weimaraner", value: "weimaraner" },
  {
    akc_code: 121,
    title: "Welsh Springer Spaniel",
    value: "welsh-springer-spaniel",
  },
  { akc_code: 221, title: "Welsh Terrier", value: "welsh-terrier" },
  {
    akc_code: 222,
    title: "West Highland White Terrier",
    value: "west-highland-white-terrier",
  },
  { akc_code: 419, title: "Whippet", value: "whippet" },
  { akc_code: 226, title: "Wire Fox Terrier", value: "wire-fox-terrier" },
  {
    akc_code: 124,
    title: "Wirehaired Pointing Griffon",
    value: "wirehaired-pointing-griffon",
  },
  { akc_code: 141, title: "Wirehaired Vizsla", value: "wirehaired-vizsla" },
  { akc_code: 865, title: "Working Kelpie", value: "working-kelpie" },
  { akc_code: 320, title: "Xoloitzcuintli", value: "xoloitzcuintli" },
  { akc_code: 670, title: "Yakutian Laika", value: "yakutian-laika" },
  { akc_code: 515, title: "Yorkshire Terrier", value: "yorkshire-terrier" },
];
